version: '3.4'
services:
    books-api:
        image: books-api
        depends_on:
            - db
        ports: 
            - "8080:80"
        build: .
        environment: 
            SQLCONNSTR_BooksDBConnectionString : ${SQLCONNSTR_BooksDBConnectionString}
            ASPNETCORE_ENVIRONMENT : ${ASPNETCORE_ENVIRONMENT}
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment: 
            SA_PASSWORD : ${SA_PASSWORD}
            ACCEPT_EULA : "Y"
    