version: '3.4'
services:
    books-api:
        image: books-api
        depends_on:
            - db
        ports: 
            - "8080:80"
        build: .
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment: 
            SA_PASSWORD : "A4SQVu9RMLJ3e2zy3sZaRsxY3RZsfj"
            ACCEPT_EULA : "Y"
    